--DROP TABLE OREMP;
--DROP TABLE ORDEPT;
--DROP TYPE emp_t FORCE;
--DROP TYPE dept_t FORCE;


CREATE TYPE dept_t;

CREATE TYPE emp_t AS OBJECT(
    EMPNO CHAR(6),
    FIRSTNAME VARCHAR2(12),
    LASTNAME VARCHAR2(12),
    WORKDEPT REF dept_t,
    SEX CHAR(1),
    BIRTHDATE DATE,
    SALARY NUMBER(8,2)
);
/

CREATE OR REPLACE TYPE dept_t AS OBJECT(
    DEPTNO CHAR(3),
    DEPTNAME VARCHAR2(36),
    MGRNO REF emp_t,
    ADMRDEPT REF dept_t
);
/

CREATE TABLE OREMP OF emp_t(
    EMPNO NOT NULL,
    FIRSTNAME NOT NULL,
    LASTNAME NOT NULL,
    CONSTRAINT emp_pk PRIMARY KEY(EMPNO)
);
/

CREATE TABLE ORDEPT OF dept_t(
    DEPTNO NOT NULL,
    DEPTNAME NOT NULL,
    CONSTRAINT dept_pk PRIMARY KEY(DEPTNO)
);
/

ALTER TABLE OREMP ADD(
    SCOPE FOR (WORKDEPT) IS ORDEPT
);
/

ALTER TABLE ORDEPT ADD(
    SCOPE FOR (MGRNO) IS OREMP,
    SCOPE FOR (ADMRDEPT) IS ORDEPT
);
/

INSERT INTO OREMP (EMPNO, FIRSTNAME, LASTNAME, WORKDEPT, SEX, BIRTHDATE, SALARY) 
VALUES('000010', 'CHRISTINE', 'HAAS', NULL, 'F', TO_DATE('14/AUG/53', 'DD/MON/YY'), 72750);

INSERT INTO OREMP (EMPNO, FIRSTNAME, LASTNAME, WORKDEPT, SEX, BIRTHDATE, SALARY) 
VALUES('000020', 'MICHAEL', 'THOMPSON', NULL, 'M', TO_DATE('01/FEB/68', 'DD/MON/YY'), 61250);

INSERT INTO OREMP (EMPNO, FIRSTNAME, LASTNAME, WORKDEPT, SEX, BIRTHDATE, SALARY) 
VALUES('000030', 'SALLY', 'KWAN', NULL, 'F', TO_DATE('11/MAY/71', 'DD/MON/YY'), 58250);

INSERT INTO OREMP (EMPNO, FIRSTNAME, LASTNAME, WORKDEPT, SEX, BIRTHDATE, SALARY) 
VALUES('000060', 'IRVING', 'STERN', NULL, 'M', TO_DATE('07/JUL/65', 'DD/MON/YY'), 55555);

INSERT INTO OREMP (EMPNO, FIRSTNAME, LASTNAME, WORKDEPT, SEX, BIRTHDATE, SALARY) 
VALUES('000070', 'EVA', 'PULASKI', NULL, 'F', TO_DATE('26/MAY/73', 'DD/MON/YY'), 56170);

INSERT INTO OREMP (EMPNO, FIRSTNAME, LASTNAME, WORKDEPT, SEX, BIRTHDATE, SALARY) 
VALUES('000050', 'JOHN', 'GEYER', NULL, 'M', TO_DATE('15/SEP/55', 'DD/MON/YY'), 60175);

INSERT INTO OREMP (EMPNO, FIRSTNAME, LASTNAME, WORKDEPT, SEX, BIRTHDATE, SALARY) 
VALUES('000090', 'EILEEN', 'HENDERSON', NULL, 'F', TO_DATE('15/MAY/61', 'DD/MON/YY'), 49750);

INSERT INTO OREMP (EMPNO, FIRSTNAME, LASTNAME, WORKDEPT, SEX, BIRTHDATE, SALARY) 
VALUES('000100', 'THEODORE', 'SPENSER', NULL, 'M', TO_DATE('18/DEC/76', 'DD/MON/YY'), 46150);


INSERT INTO ORDEPT (DEPTNO, DEPTNAME, MGRNO)
VALUES('A00', 'SPIFFY COMPUTER SERVICE DIV.', (SELECT REF(e) FROM OREMP e WHERE e.EMPNO = '000010'));

INSERT INTO ORDEPT (DEPTNO, DEPTNAME, MGRNO)
VALUES('B01', 'PLANNING', (SELECT REF(e) FROM OREMP e WHERE e.EMPNO = '000020'));

INSERT INTO ORDEPT (DEPTNO, DEPTNAME, MGRNO)
VALUES('C01', 'INFORMATION CENTRE', (SELECT REF(e) FROM OREMP e WHERE e.EMPNO = '000030'));

INSERT INTO ORDEPT (DEPTNO, DEPTNAME, MGRNO)
VALUES('D01', 'DEVELOPMENT CENTRE', (SELECT REF(e) FROM OREMP e WHERE e.EMPNO = '000040'));


UPDATE OREMP SET WORKDEPT = (SELECT REF(d) FROM ORDEPT d WHERE d.DEPTNO = 'A00') WHERE EMPNO = '000010';
UPDATE OREMP SET WORKDEPT = (SELECT REF(d) FROM ORDEPT d WHERE d.DEPTNO = 'B01') WHERE EMPNO = '000020';
UPDATE OREMP SET WORKDEPT = (SELECT REF(d) FROM ORDEPT d WHERE d.DEPTNO = 'C01') WHERE EMPNO = '000030';
UPDATE OREMP SET WORKDEPT = (SELECT REF(d) FROM ORDEPT d WHERE d.DEPTNO = 'D01') WHERE EMPNO = '000060';
UPDATE OREMP SET WORKDEPT = (SELECT REF(d) FROM ORDEPT d WHERE d.DEPTNO = 'D01') WHERE EMPNO = '000070';
UPDATE OREMP SET WORKDEPT = (SELECT REF(d) FROM ORDEPT d WHERE d.DEPTNO = 'C01') WHERE EMPNO = '000050';
UPDATE OREMP SET WORKDEPT = (SELECT REF(d) FROM ORDEPT d WHERE d.DEPTNO = 'B01') WHERE EMPNO = '000090';
UPDATE OREMP SET WORKDEPT = (SELECT REF(d) FROM ORDEPT d WHERE d.DEPTNO = 'B01') WHERE EMPNO = '000100';


UPDATE ORDEPT SET ADMRDEPT = (SELECT REF(d) FROM ORDEPT d WHERE d.DEPTNO = 'A00') WHERE DEPTNO = 'A00';
UPDATE ORDEPT SET ADMRDEPT = (SELECT REF(d) FROM ORDEPT d WHERE d.DEPTNO = 'A00') WHERE DEPTNO = 'B01';
UPDATE ORDEPT SET ADMRDEPT = (SELECT REF(d) FROM ORDEPT d WHERE d.DEPTNO = 'A00') WHERE DEPTNO = 'C01';
UPDATE ORDEPT SET ADMRDEPT = (SELECT REF(d) FROM ORDEPT d WHERE d.DEPTNO = 'C01') WHERE DEPTNO = 'D01';



--a)
SELECT d.DEPTNAME, d.MGRNO.LASTNAME 
FROM ORDEPT d
/

--b) 
SELECT e.EMPNO, e.LASTNAME, e.WORKDEPT.DEPTNAME
FROM OREMP e
/

--c)
SELECT d.DEPTNO, d.DEPTNAME, d.ADMRDEPT.DEPTNAME AS "Adiministrative_Department"
FROM ORDEPT d
/

--d)
SELECT d.DEPTNO, d.DEPTNAME, d.ADMRDEPT.DEPTNAME AS "Administrative Department", d.MGRNO.LASTNAME
FROM ORDEPT d
/

--e)
SELECT e.EMPNO, 
       e.LASTNAME,
       e.WORKDEPT.DEPTNAME, 
       e.SALARY, 
       e.WORKDEPT.MGRNO.LASTNAME AS MANAGER_LASTNAME,
       e.WORKDEPT.MGRNO.SALARY AS MANAGER_SALARY
FROM OREMP e
/

--f)
SELECT e.WORKDEPT.DEPTNO,
       e.WORKDEPT.DEPTNAME,
       AVG(CASE WHEN e.SEX = 'M' THEN e.SALARY END ) AS "Male Average",
       AVG(CASE WHEN e.SEX = 'F' THEN e.SALARY END ) AS "Female Average"
FROM OREMP e, ORDEPT d
GROUP BY e.WORKDEPT.DEPTNO, e.WORKDEPT.DEPTNAME



