#!/bin/bash

sumOdd=0
sumEven=0

for(( i=1 ; i<=$# ; i++));
do
	if [ $(( ${!i} % 2 )) -eq 0 ]
	then
		((sumEven+=${!i})) 
	else
		((sumOdd+=${!i})) 
	fi
done

echo "Sum of Odd Number : $sumOdd"
echo "Sum of Even Number : $sumEven"


