#!/bin/bash

echo "[1] Display the calendar"
echo "[2] Display the date and time"
echo "[3] Display the present working directory"
echo "[4] Display your username"
echo "[5] Create a file"                 
echo "Enter the number from above to do the relevant task : "
read num

case $num in
	1)
		cal
		;;
	2)
		date
		;;
	3)
		pwd
		;;
	4)
		echo "username is : "
		whoami
		;;
	5)
		echo "Enter the file name to be created : "
		read name
		echo "Enter the contents and press ctrl + D to save"
		cat > $name
		echo "File created and saved successfully!!!"
		;;
	*)
 		echo "you have entered an invalid type!!!"
		;;
esac


