#!/bin/bash

ls

echo "[1] copy file"
echo "[2] remove file"
echo "[3] rename file"
echo "Enter the number to perform the relevant tasks mentioned above : "
read num

if test $num -lt 1 || test $num -gt 3
then
	echo "you have entered and invalid number ...!"
	exit 1
fi

echo "Enter the name of the file : "
read name

if [ $num -eq 1 ] 
then 
	echo "Enter the correct location to be copied : "
	read location

	cp $name $location/$name
	echo "copied successfully!!!"
elif [ $num -eq 2 ]
then 
	rm $name
	echo "file removed!!!"
elif [ $num -eq 3 ]
then 
	echo "Enter the new name : "
	read newName

	mv $name $newName	
	echo "File renamed!!!"
fi


