#!/bin/bash

echo "[1] Create a directory"
echo "[2] View all files in the current directory"
echo "[3] Rename a directory"
echo "[4] View all files starting with a specific character"
echo "[5] View all files and hidden files"
echo "Enter the number from above to perform the relevant task : "
read type

case $type in
	1)	
		echo "Enter the name of the directory to be created : "
		read name
		mkdir $name
		echo "created the directory successfully!"
		;;
	2)
		ls
		;;
	3)
		ls
		echo "Enter the directory from above to be renamed : " 
		read name
		echo "Enter the new name : "
		read newName
		mv $name $newName
		echo "Directory renamed successfully!"
		;;
	4)
 		echo "Enter the starting character of the file : "
		read name
		ls $name*
		;;
	5)
		ls -a
		;;
	*)
		echo "you have entered an invalid type!"
		;;
esac



